### ISSUE TITLE
Load text on http://js9.si.edu before socket connection

### ISSUE THREAD

**Issue by cdeil** [ericmandel/js9#12]
I'm getting a timeout for http://js9.si.edu/  in Chrome from work.

![screen shot 2016-01-05 at 12 22 09](https://cloud.githubusercontent.com/assets/852409/12114064/4c28784e-b3a7-11e5-8599-078dc98483a5.png)

This might be a network / port issue on my side ... we don't have to track this down.

The issue I wanted to mention though is that the page is useless for ~ 1 minute until the timeout occurs, because the "intro", "help", ... text on the right doesn't appear until the timeout occurs.

@ericmandel Could you change the page so that the page becomes usable before that socket connection is started?

Oh, also -- happy new year!

**Comment by ericmandel** [comment]
@cdeil Happy New Year to you too!

This is actually an interesting and important problem. A 60 or so second timeout generally means that the underlying connect() system call is hung at the kernel level, which stops all program activity until connect() times out -- i.e., in this case, the page load. I'll look around to see if there is socket.io-level fix to interrupt the connect. Because even if we arranged for the page to load before the connect attempt, the browser will be unresponsive to user input during the hang.

DS9 can have a similar hang with the initial XPA connection and we added some complicated alarm code to try to sense and interrupt the hang.  If you want to see how long we've been fighting this problem (and how misunderstood it is), have a look at https://cygwin.com/ml/cygwin/2003-02/msg01931.html.

Is it only Chrome that has this problem from work? I would expect all browsers to hang. Anyway, I'll look into it.

**Comment by cdeil** [comment]
Yes, I see the same issue with Firefox and Safari.

How about migrating the docs to separate pages, or at least not have a JS9 instance on the docs landing page then?
In my opinion RST / [Sphinx](http://sphinx-doc.org/) is very nice and provides several other advantages (static URLs to docs pages / sections, table of contents, full-text search)

**Comment by ericmandel** [comment]
Well, for now, try: http://js9.si.edu/help.html, which is just a quick TOC for the help pages which reside in the js9/help subdirectory (i.e. they are already separate from the web site page).

**Comment by ericmandel** [comment]
@cdeil in an attempt to deal with your connect() hang, I added a timeout in two places. But since I can't reproduce the hang easily, I wonder if you would try to load this URL (my semi-public test page) from work and let me know what happens: 

http://mred1.cfa.harvard.edu/js9/js9debug.html

In the best case scenario, there will be a delay of approximately 10 seconds, an image will load in each of the two JS9 instances, and you will have control of the page. But that depends on how jquery and/or socket.io (separately) are dealing with the connect hang.

**Comment by cdeil** [comment]
> In the best case scenario, there will be a delay of approximately 10 seconds, an image will load in each of the two JS9 instances, and you will have control of the page.

This is exactly what is happening (I think).

**Comment by ericmandel** [comment]
If the images loaded, one of the timeouts stopped the connect() hang, reset the state of the server-side helper, and moved on to process the data files. That's probably the best we can do for this problem (although perhaps the timeout period can be shortened).

Thanks for checking this out!
