### ISSUE TITLE
Region jumps back to original position

### ISSUE THREAD

**Issue by briehanlombaard** [ericmandel/js9#17]
Hi Eric,

When I add a region to the display and try to move it while doing a bunch of `RefreshImage` calls it keeps jumping back to its original position. This is something that I think was possibly fixed in the past, but seems to have returned somewhere between v1.3 and v1.5.

In v1.8 `RefreshImage` seems to have changed quite a bit but looks more or less the same. I noticed that the variable `doreg` (which I think used to be `dobin`) is now always set to true with the old code commented out just above. Reverting that to `doreg = (this.binning.obin !== this.binning.bin);` seems to fix the issue.

**Comment by ericmandel** [comment]
Hi Briehan,

I remember this bug, but I can't yet reproduce it. Here is my first test in a JavaScript console:

1. Load a FITS image and get its im handle: var im = JS9.GetImage({display: "myJS9"})
2. Put up a region and move it off-center
3. Choose Analysis -> gaussian blur sigma, set it to 2 (for example) and click outside the menu to blur the image
4. refresh using the unblurred image data: JS9.RefreshImage(im.raws[0].hdu, {display: "myJS9"})

On my Web page, the new display is unblurred and region does not move. So we need to figure out what you are doing differently. Do you have a simple test I can try?

**Comment by briehanlombaard** [comment]
Hi Eric,

I'll see if I can get a test running online, but if I understand your test scenario correctly you aren't trying to move the region while refreshing the image?

If you can somehow put steps 3 and 4 in a loop and then try to click and drag the region somewhere else while that is happening it should illustrate the problem more clearly.

Hope that makes sense.

**Comment by ericmandel** [comment]
@briehanlombaard Thanks, I didn't quite understand the report, let me try that and get back to you.

**Comment by ericmandel** [comment]
@briehanlombaard  This is really hard to reproduce ... I think it's a race condition between the redraw and the region move. In any case, I can see how that _might_ lead to a race condition. The original logic was good, but I removed it because there were other cases where one would want to update the region positions ... and I erroneously thought we could get away with always updating. So in the code below, I have restored the old check and added more logic to try to catch these other conditions.

Can you please try this out and let me know if it works for you? It looks like it works here, but again, it's hard to reproduce.
````
    // if binning changed, we have to update the regions and other shape layers
    doreg = (this.binning.obin !== this.binning.bin);
    // restore section unless dims changed (in which case we update regions)
    if( (this.raw.width === owidth) && (this.raw.height === oheight) ){
	this.mkSection(oxcen, oycen, ozoom);
    } else {
	this.mkSection();
	this.mkSection(ozoom);
        doreg = true;
    }
````

**Comment by briehanlombaard** [comment]
That seems to fix it. Thanks for looking into it.
