### ISSUE TITLE
Side by side images in the same JS9 display (mosaic mode)

### ISSUE THREAD

**Issue by nicolaschotard** [ericmandel/js9#36]
@ericmandel Is it possible to put 2 images side by side on one single JS9 display? 

The idea would be to automatically (or optionally) do that for multi-extension fits files in order to create a mosaic image that can automatically display the full focal plane (using WCS info), as it can be done with ds9. 

Thanks in advance for any advice on how to achieve that!

**Comment by ericmandel** [comment]
@nicolaschotard You certainly can have multiple JS9 display elements in a single web page as shown in https://js9.si.edu/js9/js9multi.html. You would just lay out the JS9 display elements according to your mosaic pattern and then load each image into the appropriate element. You can even have a supermenu control all of the elements, or each one individually, as shown in https://js9.si.edu/js9/js9super.html.

Not having much experience with DS9 mosaics, I'm not sure what is needed to get the JS9 elements placed properly ... so that might require some work, either on your part or on mine. Let me know what is missing in this regard and we'll figure out what to do.

**Comment by nicolaschotard** [comment]
Thanks for your quick answer @ericmandel I understand your solution of organizing all the individual JS9 displays next to each other in an order that corresponds to the real disposition of the images on the focal plane. I was more thinking about having a unique display containing all the images. 

I will think about a way to do that, but there is nothing obvious to me on this side.

**Comment by ericmandel** [comment]
@nicolaschotard Can you explain the advantage of having a single display containing multiple images over multiple displays with a single image each, all controlled by the supermenu?

Aside from that question, I think a mosaic plugin can be implemented like the blending plugin (which also composes the display from multiple images, but places them on top of one another). In this scenario, you load a bunch of images and then mosaic them into a single display.

Instead of parameters that describe the image blend mode and opacity, we would need to parameterize the offsets into the display for each image.  Right now, the im.ix and im.iy internal properties tell JS9 where to place an image in the display, using im.calcDisplayOffsets(). 
This would have to be generalized to take the mosaic mode into account. But if I added support for an oncalcdisplayoffsets event callback inside im.calcDisplayOffsets(), the plugin could be asked to return the offsets for a given image. That might be pretty easy.

Are there  parameters inside the FITS header that would give a hint about how to place the individual images? Or is this specified manually? Or both? That question affects the mosaic plugin user interface.

**Comment by nicolaschotard** [comment]
I was think of one single display containing all images to be able to zoom in or out over the entire field, for example, as we do in ds9. Is the the super menu you are talking about able to take care of things like that? 

I do not know how ds9 is exactly working, but it definitely uses the WCS info contained in the header to do that. The command line I usually use is 
```
ds9 -mosaicimage wcs -zscale myMultiExtensionImage.fits.fz   # wcs or iraf
OR
ds9 -mosaic wcs -zscale *.fits.gz  # for a list of one-extention files
```

**Comment by ericmandel** [comment]
Ah, yes ... now I see what you want to do. Right now, the super menu would not handle zoom and pan across all images, as you want, but that might (or might not!) be easy to add. So I am not yet sure special mosaic code would be needed.

Let me think a bit about how best to support a mosaic of images in JS9. If you have test files, that might be helpful. Otherwise, I'm sure Bill has some for DS9.

This is an interesting feature, thanks for bringing it up!

**Comment by nicolaschotard** [comment]
Here is one file that you can download. This is a CFHT image.

http://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/data/pub/CFHT/1022360p?runid=tqz472jgnzim7r6l

**Comment by ericmandel** [comment]
Got it. Very interesting. Give me a few days to experiment and think ...

**Comment by nicolaschotard** [comment]
Thanks a lot for all this effort! And let me know if you need any input from me, or if you need someone to do some test.

**Comment by ericmandel** [comment]
Thanks, I'll rely on you to evaluate that things are working and are acceptable. This probably is not a quick fix, so let's get it started. (And anyway, I can't figure out a satisfactory way to label the axes on the coordinate grid, happy to put it off!)

**Comment by ericmandel** [comment]
@nicolaschotard I've made some experiments to investigate how best to do mosaics in JS9. Unlike DS9, we have to generate a mosaic of the underlying raw data as well as the display data, so that user plugins continue to work. Stitching together the mosaic images manually (i.e. placing each image pixel from each mosaic in a super-mosaic array) got to be a mess, but using IPAC's Montage programs (some of which are already incorporated into JS9 using emscripten) shows a lot of promise.

Before I go ahead, I wonder if you would play with the attached script (renamed from mkmosaic to mkmosaic.txt because of GitHub) that uses Montage (and the JS9 js9helper program) to produce a mosaic image along the lines I am considering. You need to install Montage (see: http://montage.ipac.caltech.edu/) and also build the js9helper program, if you have not already done so. Then you can run the script on the CFHT image you sent me and see its promise and some of the issues:

1. Most importantly, we can't simply make an unbinned mosaic: it is much too large to display in a browser (DS9 has access to virtual memory via the mmap() call, browsers do not).  It also takes a very long time. Therefore the script makes a binned mosaic (using the -b <bin> switch, default is 8) and I propose that JS9 support user-specification of a bin factor (or perhaps calculate this automatically). You will, of course, be able to view each unbinned image of the mosaic separately. Is this acceptable?

2. Using the image you sent, the IPAC Montage software produces a mosaic which is flipped in both x and y with respect to what DS9 displays. I don't know why DS9 does this, but I propose to display what Montage produces, and add flip capabilities to JS9 so that you can flip the Montage-produced mosaic if needed. Is this acceptable?

I'm finishing up JS9 v2.2 and can do more work on mosaics after that, if the plan seems good to you.

[mkmosaic.txt](https://github.com/ericmandel/js9/files/1948117/mkmosaic.txt)

**Comment by ericmandel** [comment]
@nicolaschotard I've implemented mosaic support along the lines described above (though I have not implemented flip support). As before, loading the test CFHT file will display the first extension and allow display of the others through the View -> Extensions plugin. But then choose:

File -> create mosaic ... -> the current image

and a binned (to fit into memory) mosaic will be generated. For the CFHT image, this takes about 30 seconds, more or less the same as DS9.  Also, several related images can be loaded into one JS9 display and mosaic'd into one image:

File -> create mosaic ... -> all image in this display

The mosaic image is kept separate from the originally displayed image, so you can go back and forth between the larger, binned view and the individual pieces of the mosaic.

It works for projections which can be approximated by tangent-plane projections (TAN, SIN, ZEA, STG, ARC). Other projections would require use of the full Montage mProject code, which takes a very long time to run. I'm not ready to do that yet ...

**Comment by ericmandel** [comment]
@nicolaschotard I'll close this issue, but feel free to open another one if you find a problem with the current implementation.
