### ISSUE TITLE
configure script not finding cfitsio on Ubuntu

### ISSUE THREAD

**Issue by o-smirnov** [ericmandel/js9#39]
I've got the standard ``libcfitsio3-dev`` Ubuntu package installed, but I couldn't get ``configure`` to recognize it. Tried ``--with-cfitsio=/usr`` and the like, but it wasn't finding it.

I was forced to build a second copy of cfitsio from scratch, and install it to ``/usr/local``, the config script could then find it there.

This is probably due to the directory layout in Debian/Ubuntu, see below. I don't think the script knows to look in ``x86_64-linux-gnu``.

```
$ dpkg -L libcfitsio-dev
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libcfitsio-dev
/usr/share/doc/libcfitsio-dev/copyright
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libcfitsio.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/cfitsio.pc
/usr/include
/usr/include/fitsio2.h
/usr/include/drvrsmem.h
/usr/include/fitsio.h
/usr/include/longnam.h
/usr/share/doc/libcfitsio-dev/changelog.Debian.gz
/usr/lib/x86_64-linux-gnu/libcfitsio.so
```

**Comment by ericmandel** [comment]
Right, I look manually in places I know about underneath the specified directory, not knowing any easy way to do otherwise.

Try the attached version of configure (renamed to configure.txt to make GitHub happy), which should work, in your case, with:
````
--with-cfitsio=/usr 
````
If it works, I'll update it into GitHub.


[configure.txt](https://github.com/ericmandel/js9/files/2166565/configure.txt)

**Comment by o-smirnov** [comment]
No joy:
```
./configure1 --with-cfitsio=/usr --with-webdir=/home/oms/radiopadre/js9-www --with-helper=nod |grep cfitsio
checking for cfitsio... no
no funtools or cfitsio: back-end programs will not be built
```

**Comment by ericmandel** [comment]
Right, I just edited my comment to say 'wait', as I see I have a problem. Give me a minute, I need to figure out how to test this on my Mac.

**Comment by o-smirnov** [comment]
If you want a login on an Ubuntu box here for testing, I'm happy to provide....

**Comment by ericmandel** [comment]
Thanks, let's try this new configure and, if it fails, I'll accept your offer.

[configure.txt](https://github.com/ericmandel/js9/files/2166713/configure.txt)

**Comment by o-smirnov** [comment]
That works!

**Comment by ericmandel** [comment]
Great, it works here too, and the change is now updated into GitHub ...

**Comment by o-smirnov** [comment]
Hmmm, deja vu strikes back in 3.1:

```
$ cd js9-3.0
$ ./configure --prefix=/home/oms/.radiopadre/venv --with-webdir=/home/oms/.radiopadre/venv/js9-www --with-helper=nodejs --with-cfitsio=/usr
...
checking for cfitsio... yes (/usr)
...
$ cd ../js9-3.1/
$ ./configure --prefix=/home/oms/.radiopadre/venv --with-webdir=/home/oms/.radiopadre/venv/js9-www --with-helper=nodejs --with-cfitsio=/usr
...
checking for cfitsio... no
...
$
```
I'll flee back to 3.0 for now...

**Comment by ericmandel** [comment]
@o-smirnov Weird ... there are no relevant changes in configure.ac from 3.0 to 3.1, but I did upgrade autoconf from 2.59 to 2.69, so the configure scripts are very different. Can you post a more detailed log?

**Comment by o-smirnov** [comment]
Sure, console log: [console.log.txt](https://github.com/ericmandel/js9/files/5433326/console.log.txt)

config.log: [config.log.txt](https://github.com/ericmandel/js9/files/5433327/config.log.txt)

**Comment by ericmandel** [comment]
Oh Lord have mercy ... looks like config.guess has changed its description of Ubuntu. Can you please do a test by editing the 3.1 configure script and making this change and trying again:
````
diff ../ojs9/js9-3.1/configure configure
3286c3286
< OSSUFFIX=`echo $host | sed 's#-unknown##'`
---
> OSSUFFIX=`echo $host | sed 's#-[^-]*##'`
````
I clearly need a better way to figure out if cfitsio is in a system location, but at least I can add this patch for now ... if it works.

**Comment by o-smirnov** [comment]
Yep, that works. Thanks!

Are you going to push a new point release with it in place?

**Comment by ericmandel** [comment]
We're close ... I believe I have fixed this properly, so that you can just do this:
````
with-cfitsio
````
instead of
````
with-cfitsio=/usr
````
and have configure use -lcfitsio from the system location (i.e. without -L). Would you please rename the attached configure.txt to configure, make the change above in your build script, and test? It works on my 2006 Core2Duo machine running Ubuntu.

I can then push this change to the repository today.  A full, official v3.2 release is coming soon. Most of the changes in this release are in support of our upcoming Desktop app called Voyager, so from your point of view its very similar to v3.1.

[configure.txt](https://github.com/ericmandel/js9/files/5434586/configure.txt)

**Comment by o-smirnov** [comment]
Sorry, close but no cigar. Finds it with ``with-cfitsio=/usr``, doesn't find without. I attach config.log.
[config.log.txt](https://github.com/ericmandel/js9/files/5438188/config.log.txt)

**Comment by ericmandel** [comment]
> ./configure --prefix=/home/oms/.radiopadre/venv --with-webdir=/home/oms/.radiopadre/venv/js9-www --with-helper=nodejs

You have to add:
````
--with-cfitsio
````
to tell configure to build the back-end using a cfitsio library located in a system directory. Otherwise it doesn't even try ...

> close but no cigar

omg, my 1st generation father said this all the time! Is it the translation of a Russian idiomatic expression??

**Comment by o-smirnov** [comment]
Ah but of course, sorry! Yes, with just ``--with-cfitsio`` it all works.

> omg, my 1st generation father said this all the time! Is it the translation of a Russian idiomatic expression??

Hmmm, not that I know of... in fact smoking cigars isn't even a particularly Russian thing (my profile picture, and the long Soviet friendship with Cuba notwithstanding...)

**Comment by ericmandel** [comment]
@o-smirnov I've pushed the new configure.ac/configure. but I assume you want a release point instead of using the working repository ... I expect v3.2 in a week or two (ok, famous last words!) ... I'm working on the last anticipated change,  but also waiting for bug reports. Perhaps you might want to run radio-padre through its paces using the working repository in the meantime?

In any case, thanks for  "close but no cigar" ... hadn't thought of it for decades!

**Comment by o-smirnov** [comment]
[Clearly, I need to be going to more carnivals.](https://en.wiktionary.org/wiki/close,_but_no_cigar#:~:text=Etymology,failed%20to%20win%20a%20prize)

**Comment by ericmandel** [comment]
I'm looking forward to going ... anywhere! But if we can't, no problem ... we can use that phrase in practically all software discussion from now on ...

**Comment by o-smirnov** [comment]
> we can use that phrase in practically all software discussion from now on ...

"All" seems a little generous of you. If my own software is anything to go by, this phrase should be applicable 9.9% of the time at most (with "not even in the ballpark" accounting for another 90%). But we live for that 0.1% of course!

**Comment by ericmandel** [comment]
@o-smirnov v3.2 is now released and I will look forward to making a patch 3.2.1 for you in the very near future ... 

(but at least my at-home Linux setup now installs cfitsio in a system location, so hopefully that bug will not happen again.)
