### ISSUE TITLE
Is it possible to save full size image from blending or RGB mode?

### ISSUE THREAD

**Issue by cylammarco** [ericmandel/js9#51]
I am trying to make a button for an outreach webpage, targetting primary and secondary school, to save PNG and JPG file after making false-color images. The teachers' opinion is that having a menu bar is too confusing to the students, so I was trying to add a button for them to save the false colour image with 
`JS9.displays[0].image.saveIMG()`
but the image size is defined with the display size. Is it possible to re-render/reproject the image at the back and save the image at a higher resolution?

**Comment by ericmandel** [comment]
I think its great that you are simplifying the interface for students!

By "higher resolution", do you mean saving RGB pixels outside the display in the PNG (or JPG) file? If so, I don't think you can do that: the only RGB pixels we generate are those being displayed. You can see this here, where the image data is 2048x2048, but the RGB image size is smaller to match the display size:

<img width="1185" alt="screen shot 2018-12-04 at 8 06 27 am" src="https://user-images.githubusercontent.com/3028875/49443956-c6acb900-f79b-11e8-8dae-0bbd3068285b.png">

(If we don't clip like this, contrast/bias changes would take forever, for example, as we process pixels not seen). 

Is there a reason why you can't resize the display so that it shows the larger image? This could be done when you define the JS9 element in the page (data-width="xxx", data-height="yyy") or at runtime with a button that executes:
````
JS9.displays[0].resize(width, height)
````
or a select menu, etc.

**Comment by cylammarco** [comment]
Thanks!

Yes, that is what I meant. I didn't think about the problem with speed. That makes sense.

To go round this, (1) I am copying the image and the image parameters to a hidden JS9 display at the required width and height. (2) A jpg/png is then saved from that background display; finally, (3) call the `JS9.CloseDisplay()` to clear the background display.

I'm now trying to execute (1), (2) and (3) sequentially, from a single click.

**Comment by ericmandel** [comment]
So are you doing a deep clone of the image object, changing the display property to point to the new display? If haven't thought about this much, but it might work.

One place you will have trouble is in the asynchronous nature of the save routine. You will have to set a timeout before you do the close, or else you can run into a race condition. If necessary, I can add a callback capability to the save, but try the timeout first to see if this is going to work at all.

**Comment by cylammarco** [comment]
Yes, I would like to clone the image object. I am simply loading the same image into both the working and the background hidden displays. It is slow, but it works for now... There may not be a broad use case, but if there is a `copyToDisplay` function like the `JS9.Image.prototype.moveToDisplay`, it would help. I am likely to look into that in the future if this function is too specific for my case only.

The asynchronous nature is indeed causing a little problem. I am yet to test on a slow computer and see how long a buffer time I should add. Currently, I set a wait time of 1 second, which work on both my phone and my laptop.

**Comment by ericmandel** [comment]
I'm a little hesitant about this function, because it seems to bypass the guard-rails we try to put in place when dealing browser memory limits. If the original image is very large (yesterday we were considering our options with a 20k x 20k FITS image), you'll likely blow up when you try to create a full size png/jpg. But let me think about this more, while you play with your current implementation.
