### ISSUE TITLE
Please give guidance on integration into a Single Page Application

### ISSUE THREAD

**Issue by d-w-d** [ericmandel/js9#60]
SPAs (react, angular, etc.) will, in general, be adding the salient <div class="JS9"> to the DOM **after** initial load of html with the js9 js files. I'm not finding it easy to understand how the scripts in "js9basics.html" operate on the above div. Is it upon some 'DOMContentLoaded' event that the div is transformed from `<div class="JS9"></div>` to `<div class="JS9" id="JS9" style="width: 516px; height: 516px; resize: both; overflow: hidden; position: relative;">`, etc.? If so (or otherwise), could you give some advice/documentation on what needs to happen when one dynamically adds a <div class="JS9"> to the DOM? Thanks.

**Comment by ericmandel** [comment]
After the DOM is ready, JS9.init() is called and a whole bunch of things happen to get JS9 ready: transforming the JS9 divs of various classes, retrieving and compiling the wasm code, initializing FITS library, etc. When all of this is done and JS9 is really ready for user processing, a "JS9:ready" event is emitted, after which you can do your own processing:
````
      $(document).on("JS9:ready", function(){
	  myinit();
      });
````
If you want to add new JS9 displays on the fly, you have a number of options: you can add a new display in a light window, to the page itself, or in an entirely new window.  These are detailed in the demo: https://js9.si.edu/js9/js9create.html. The key to adding a JS9 display div to the current page is to create the div and then call the public access routine JS9.AddDivs, which is documented at: https://js9.si.edu/js9/help/publicapi.html#JS9.AddDivs

> SPAs (react, angular, etc.) will, in general, be adding the salient 

I don't have a lot of experience with these, so we might to fiddle a bit as we learn how they interact with JS9.

**Comment by dwd-umd** [comment]
Thanks @ericmandel. I've got a basic integration working that makes primary use of `JS9.AddDivs`. However, for now, I've had to use `setTimeout` to give JS9 time to do it's stuff under the hood. This is roughly the JS that gets fired after my SPA adds a div of class="JS9" and id="myId"

```
      // Add div to JS9 displays
      JS9.AddDivs('myId');

        // JS9 seems to require some settling time before we can load a fits file
      setTimeout(() => {
        // Load external fits file to our div
        JS9.Load(this.fits_url, { scale: 'log' }, { display: 'myId' });
        // JS9 seems to require some settling time before we can zoom programmatically
        setTimeout(() => {
          JS9.SetZoom(2, { display: 'myId' });
        }, 1000);
      }, 1000);
```

So, I'm having to give it some time (1000ms chosen somewhat arbitrarily) to first do the JS9.addDivs, and then more time to zoom programmatically. It would be much nicer if there were events that I could listen for once these sorts of tasks are complete. Any suggestions? Thanks.

**Comment by ericmandel** [comment]
Hi @dwd-umd, you can and should use JS9.Preload() instead of JS9.Load(), since JS9.Preload() will check to make sure everything is ready. Also, you can use the onload callback to set the zoom after loading. Here is a slightly bizarre example, copied from https://js9.si.edu/js9/js9debug.html:
````
        JS9.Preload("./fits/casa.fits[events][energy=3000:7000]",
                    {colormap: "cool", contrast: 5.9, bias: 0.66, scale: "log",
                     xdim: 8192, ydim: 8192, bin: 4,
                     onload: function(im){
                       JS9.SetZoom(2);
                       JS9.LoadRegions("casa/casa.reg");
                       JS9.Load("fits/ngc1316.fits",
                                {colormap: "viridis", scale: "linear",
                                 onload: function(im){
                                   JS9.SetScale("zscale", {display: im});
                                   JS9.Load("fits/casa.fits");
                                 }});

                    }}); 
````

**Comment by ericmandel** [comment]
A few  random notes:

As shown above you can set the zoom right in the Preload() or Load command by passing a opt object:
````
JS9.Preload("foo.fits", {zoom: 2});
````
See https://js9.si.edu/js9/help/publicapi.html#JS9.Load for more details.

If you want have other initialization functions to perform and want to wait for JS9 to be ready, you can wait like this:
````
$(document).on("JS9:ready", function(){
	  myinit();
});
````
Sorry, I thought had documented this better than I have ... I'll fix that ...

You can even delay calling JS9.init() and do it manually, as described in https://js9.si.edu/js9/help/webpage.html:
````
 Normally, JS9 will initialize itself automatically once the page is loaded and ready: internally, jQuery $(document).ready() calls JS9.init(). If you need to delay JS9 initialization (e.g., you are using a platform that fires $(document).ready() before the platform is really ready), you can set data-js9init to "false" on any JS9 div. In this case, you must call the init routine manually:

  JS9.init();

Until you do this, no JS9 div elements will be visible. 
````
This might make it unnecessary to call JS9.AddDivs(). Although I suspect this technique has been little-used, it might be appropriate in cases where you can't use the "JS9:ready " event. Let me know if you try it ...

**Comment by dwd-umd** [comment]
Thanks very much Eric for the helpful info. You can see what I've got so far here (click on thumbnail to open JS9 in dialog): [Code](https://github.com/dwd-umd/catch-gui/tree/010-improveJS9Loading) / [Deployment](https://oort.astro.umd.edu/catch-gui/010-improveJS9Loading/)

Here's the essence of what I'm doing at the moment. The JS9 scripts are included in the index.html as standard, so JS9 initializes automatically. When the dialog opens I generate a unique id and use it to associate divs for JS9, JS9 Menubar and JS9 Color bar. Once those standard divs are rendered in the DOM, I then run `JS9.AddDivs(unique_id)` and then `JS9.Load(...)` to add the FITS file.

If the dialog closes and another one is opened then I generate a new unique id and go through the same process again. This seems to work ok, however, please note the following comments/questions:

1. Can you confirm please that JS9.AddDivs() is synchronous? I.e. JS will not move onto the next line until this function is done manipulating the DOM. It seems to act fast and I don't see any sort of on-complete call-back option. 
2. I haven't sensed a need yet for using `Preload` as you suggested. Could you explain what you meant by "JS9.Preload() will check to make sure everything is ready"? Does this mean that it will wait for e.g. JS9.AddDivs to complete?
3. When I close a dialog, are there any still-ongoing processes that got started by JS9.AddDivs() and/or JS9.Load() that I need to worry about and, ideally, terminate? I don't want memory to get used up more and more as the user opens/closes dialogs.
4. I tried to get the JS9 elements to reload on window-resize events; I got the main JS9 image to adapt OK, but the colorbar seems much harder; any thoughts on this?

Much appreciated!

**Comment by ericmandel** [comment]
Your web site is gorgeous! I wish I could do something that nice. I only had a quick look in the crush of today's activity, and didn't see the js9 thumbnail. Can you tell me where it is?

> Can you confirm please that JS9.AddDivs() is synchronous? I.e. JS will not move onto the next line until this function is done manipulating the DOM. 

JSs9.AddDivs is synchronous but NB: it does not do anything at all to the DOM, it assumes that the DOM elements have already been added. All it does is make sure that newly added JS9 divs are configured properly, e.g. JS9 plugins are instantiated.

When you add to the DOM, does that happen asynchronously? If that is so (something I did not know), then you probably have to wait until the divs have been added before calling JS9.AddDivs(). For observing changes to the DOM, I've been using https://github.com/uzairfarooq/arrive, but I don't if new and better techniques have come along in the past few years. I do something like this:
````
// when window has been loaded and uwin id is available, move the display
$("#dhtmlwindowholder").arrive("#" + uwin, {onceOnly: true}, function(){
    uim.moveToDisplay(uwin);
});
// load the window
JS9.LoadWindow(null, {id: uwin, clone: udisp.id}, "light");
````
So I do wonder if this is the source of some of your problems.

> Could you explain what you meant by "JS9.Preload() will check to make sure everything is ready"? Does this mean that it will wait for e.g. JS9.AddDivs to complete?

No, what it does it wait for all of the async init tasks to complete.  For example, if you are running a JS9 helper to deal with server-side tasks, the browser has to connect to that helper and exchange a bit of information. Preload() knows how to wait for that. We wrote Preload() to allow developers to do this:
````
<body onload="init()">

function init(){
  JS9.Preload("foo.fits")
}
````
because that seemed like a pattern people wanted to do ... although JS9 is  nowhere near ready when that call fires. Now, you can also do this:
````
      $(document).on("JS9:ready", function(){
          init();
      });
````
and in this case, JS9:ready really means ready, so you can just do a Load instead of a Preload.

> When I close a dialog, are there any still-ongoing processes that got started by JS9.AddDivs() and/or JS9.Load() that I need to worry about and, ideally, terminate?

No, I don't think there is anything left over from a dialog.

> I tried to get the JS9 elements to reload on window-resize events; I got the main JS9 image to adapt OK, but the colorbar seems much harder; any thoughts on this?

Resize should happen automatically to all divs defined in the JS9.globalOpts.resizeDivs property, which contains these divs, by default: ["JS9Menubar", "JS9Colorbar", "JS9Toolbar"].

... I just changed the size of an image to 400,400 and the menubar, toolbar, and colorbar did resize as well. But perhaps I am missing something?

**Comment by dwd-umd** [comment]
Thanks! Some quick points:

- "[I] didn't see the js9 thumbnail. Can you tell me where it is?" --> If you go to the [link above](https://oort.astro.umd.edu/catch-gui/010-improveJS9Loading/) you light to see a table with three rows. The clickable (placeholder) thumbnails are in the far left column.

- Just to clarify, when I say 'resizing', I mean if you make the browser window smaller then the elements in my dialog wrapping the JS9 elements will shrink and, with them, the JS9 elements. From you wrote it sounds like your resizing mechanism is based upon some sort of dynamic resizing of the FITS file. Is that right? In any case, I'd decided to drop trying to resize my JS9 viewer in response to user-induced window resizing (since that's a niche occurrence).

**Comment by ericmandel** [comment]
Thanks, I'll look forward to trying it out tomorrow ... 

You can dynamically resize the JS9 display by grabbing the handle in the lower right corner and moving it, or by using the View -> resize ... menu option or the JS9.ResizeDisplay() call. Ah, this is different from resizing the browser itself ... I have no idea what happens when you do that, and will be happy to leave it to another time ...

**Comment by ericmandel** [comment]
Oh, beautiful! I didn't get any of that when I loaded the page this morning, just the really cool background. That's really nice!

**Comment by ericmandel** [comment]
> When I close a dialog, are there any still-ongoing processes that got started by JS9.AddDivs() and/or JS9.Load() that I need to worry about and, ideally, terminate? I don't want memory to get used up more and more as the user opens/closes dialogs.

Now that I've seen that the dialog contains a JS9 display, I understand the question better. When the dialog is destroyed, you're going to want to make sure you call JS9.CloseImage() to free up all the resources associated with that image. But there are no extra processes running that you have to terminate.

**Comment by dwd-umd** [comment]
Thanks. Also, what option is needed to add to `JS9.globalOpts.userMenuBar ` [here](https://github.com/dwd-umd/catch-gui/blob/master/src/app/dynamic-pages/fits-dialog/userMenuSettings.js) in order that my drop-down 'Scale' menu can have `Data Limits` fields when my JS9 is set to `data-style="Mac"`?

**Comment by ericmandel** [comment]
You should be able to use "SetScale" as the cmd and "dataminmax", "zscale",  or "zmax" as the  single string argument passed on the args array:
````
	    {
                ....
		"cmd": "SetScale",
		"args": ["dataminmax"]
	    }
````

**Comment by dwd-umd** [comment]
sorry, I'm not following. My goal is to create something close to this image

<img width="186" alt="Screen Shot 2019-07-18 at 10 53 58 AM" src="https://user-images.githubusercontent.com/45804559/61468803-1b2c2f80-a94c-11e9-987c-c3195fdf3929.png">

... but starting from the customized menubar initiated by html like:

```html
      <div
        #js9MenuRef
        [id]="uid + 'Menubar'"
        class="JS9Menubar"
        [attr.data-width]="js9Width"
        data-style="mac"
        data-usermenus="true"
      ></div>
```

My understanding of your suggestion was to set my `JS9.globalOpts.userMenuBar` array to the following:

```js
[
  ...,
  {
    name: 'scale',
    title: 'Scale',
    updateTitle: 'text',
    options: [
      {
        name: 'linear',
        cmd: 'SetScale',
        args: ['linear']
      },
      {
        name: 'log',
        cmd: 'SetScale',
        args: ['log']
      },
      {
        name: 'histeq',
        cmd: 'SetScale',
        args: ['histeq']
      },
      {
        name: 'Data Min Max',
        cmd: 'SetScale',
        args: ['dataminmax']
      }
    ]
  },
  ...
];
```

... but this resulted not in the addition of two extra text input fields in the drop down menu (for low and high), but just another menu item labeled `Data Min Max` (that doesn't do much). You can see this array implemented [here](https://oort.astro.umd.edu/catch-gui/v3?dest=neat).

**Comment by ericmandel** [comment]
Oh, sorry, I thought you were tying to do this:

<img width="354" alt="Screen Shot 2019-07-18 at 11 26 03 AM" src="https://user-images.githubusercontent.com/3028875/61470403-056c3980-a94f-11e9-9f9e-d1b6b666c6bb.png">

I can look into this, but adding a text input option to the user menus will be difficult, the text input handling doesn't seem to be amenable to the sort of generalization that would be required.

**Comment by ericmandel** [comment]
@dwd-umd BTW, you can bring up the Scale Controls plugin from your user menu ... which will allow you to set data min and max. Just add something like this:
````
	    {
		"name": "Scales...",
		"cmd": "DisplayPlugin",
		"updateTitle": false,
		"args": ["JS9Scale"]
	    }
````
See the demo at: https://js9.si.edu/js9/js9menustyles.html
