### ISSUE TITLE
Failed to compile JS9 with Vue: error  in ./node_modules/js9/js9support.css

### ISSUE THREAD

**Issue by miguelcarcamov** [ericmandel/js9#61]
Hi there, 

I am trying to use Vue and JS9 to display some radio astronomical images in my web pages. Specifically, I am trying to install JS9 with npm.

After installation, I do 
npm run build to compile.

And I get the following error:

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                               15:13:00

 error  in ./node_modules/js9/js9support.css

Module build failed (from ./node_modules/@vue/cli-service/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './indentbg2.gif' in '/home/miguel/Documents/gpuvmem-web/node_modules/js9'
```

Checking where the indentbg2.gif is, I realized that the path should be ./images/indentbg2.gif instead of just ./indentbg2.gif

Is this a bug? Or I have done something wrong?

Best regards

**Comment by ericmandel** [comment]
@miguelcarcamov We'll have to work together on this, as I don't have much experience with npm, aside from building the JS9 npm package itself in the simplest way possible. And I don't know anything about Vue ...

That said, there is no "run" or "build" directive in the the JS9 package.json file: you should be able to use JS9 immediately out of the box, once its installed. If you do need to build some of the support programs (e.g. you want to use the server side analysis or large file support), I think you'll have to build manually by running a configure command and then doing the make yourself.  If this can be automated within npm, I'd appreciate help learning how to do it!

**Comment by miguelcarcamov** [comment]
hi @ericmandel, yes... don't worry it is a pleasure to work with you in this issue. 

For now I am trying to give JS9 the URL path to some fits file. However, I realize that in the examples provided, specifically when we use the function preLoad() , it has a parameter called: fits, that is a fits.gz file, and parentfile, which is the real fits file... Why is this?

-> This solution is not currently working... JS9 gives an error saying that the file in the URL does not exist.
-> We also tried to give JS9 the absolute path to a fits file, however JS9 gives the following error: ERROR from cfitsio.js: error reading from FITS file.

Do you know the reason of that?

I am also trying to connect vue with the npm version of JS9, it will take time but hope we could do it... 

Best regards

@JavierArredondo is also working with me on this and probably will ask you questions in this same thread.

**Comment by ericmandel** [comment]
When JS9 is used inside a web page, the first argument of  JS9.PreLoad() or JS9.Load() is the path of the FITS file __relative to the web page__ from which it is being loaded. For example, on the main JS9 web site, https://js9.si.edu, the Cas-A FITS file is loaded with this call:
````
JS9.Preload("js9/fits/casa.fits.gz", obj);
````
and casa.fits.gz file is located in a subdirectory called fits of the js9 directory, which itself is below the directory containing index.html.

The parentFile is something you don't need to worry about immediately. The issue is this: if you have a very large FITS file, you probably do not want to download it into the browser, since it will take a long time. Instead, you can download a much smaller __representation FITS file__, perhaps a highly blocked image. But you might want to perform server-side analysis on the original very large FITS file. This is where you specify the parentFile parameter: it tells JS9 that server-side analysis should be performed on the large parentFile, not the small representation file. For example, on the main https://js9.si.edu web site, the Cas-A FITS file that gets automatically loaded (and which you see) is a 290Kb FITS image, but the parentFile is 33Mb and that is what is used for server-side analysis:
````
obj = $.extend(true, {}, objs[idx]);
obj.parentFile = "fits/casa.fits";
JS9.Preload("js9/fits/casa.fits.gz", obj);
````
(You might notice the unfortunate fact that the path of the parentFile is not relative to the web page, but is relative to the directory in which the JS9 helper is running. As I said, you don't need to worry about this at the start.)

**Comment by JavierArredondo** [comment]
Hi there, 

We can work in a new package of JS9 for npm with @miguelcarcamov and publish this in **npm**.
Actually I need this module for 2 projects: ALeRCE and GPUVMEN. 

I hope you can explain to me how the tool works in detail for build some...

**Comment by ericmandel** [comment]
Yes, I can help you with questions. But I also recommend that you look at the demos on the main web page https://js9.si.edu. They explain some of the features of JS9, and you can see the code working in a real web page.

**Comment by miguelcarcamov** [comment]
@JavierArredondo maybe you can start explaining what is the problem that we are currently having trying to connect js9 to the gpuvmem web page.

**Comment by ericmandel** [comment]
please include JS9 messages you see in the JavaScript console, if any ...

**Comment by miguelcarcamov** [comment]
Do you have a Slack group for JS9 where it could be easier to contact you and show you the errors and the messages?

**Comment by ericmandel** [comment]
No, sorry, but we can do it via email eric@cfa.harvard.edu, which might be easier to pass files ...

**Comment by ericmandel** [comment]
Can I access the website myself?

**Comment by miguelcarcamov** [comment]
We are currently trying to load or preload images using CORS, it is possible to preload or load images from dropbox, since we have not control of the js9 configuration on the server side?

**Comment by ericmandel** [comment]
@miguelcarcamov Yes, JS9.Load() should be able to load CORS files directly, since there will be no problem with same-origin policy.  There actually is a menu option in the File menu that allows you to enter a Dropbox URL and it should load it properly. I haven't tried this lately, so let me know if there is a problem and I will fix it.

But ... you also should look at the JavaScript code in the Run button on the params/loadcors.html to see what tricks I had to use to load a Dropbox file successfully. You probably will have to do something similar to your URLs before loading them.

Let me know how it goes ...
