### ISSUE TITLE
CORS policy error with a local file

### ISSUE THREAD

**Issue by andreatramacere** [ericmandel/js9#62]
I am getting CORS policy error when working on a naive example using mac os 10.12.6. This happens with all the browsers.

```
<html>
            <head>
              <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
              <meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1" > 
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <link type="image/x-icon" rel="shortcut icon" href="./favicon.ico">
              <link type="text/css" rel="stylesheet" href="https://js9.si.edu/js9/js9support.css">
              <link type="text/css" rel="stylesheet" href="https://js9.si.edu/js9/js9.css">
              <script type="text/javascript" src="https://js9.si.edu/js9/js9prefs.js"></script>
              <script type="text/javascript" src="https://js9.si.edu/js9/js9support.min.js"></script>
              <script type="text/javascript" src="https://js9.si.edu/js9/js9.min.js"></script>
              <script type="text/javascript" src="https://js9.si.edu/js9/js9plugins.js"></script>
                </head>
            <body>


            <center><font size="+1">
            </font></center>
            <table cellspacing="30">
            <tr valign="top">
            <td>	
            </td>
            <td>	
            <tr valign="top">
            <td>
            <div class="JS9Menubar"></div>
            <div class="JS9"></div>
            </td>
            <td>
            
            <p>
            </td>
            </tr>
            </table>
            <script type="text/javascript">
              function init(){
                 var idx, obj;
                  
			      JS9.Preload("js9/test.fits");
              }
              $(document).ready(function(){
                init();
              });
            </script>
            
        </body>
</html>
```

**Comment by ericmandel** [comment]
Yes, CORS prevents you from accessing an image whose origin is different from the origin of the JavaScript code being used to do the access. You are loading remote JS files and trying to access a local image, which is not permitted.

If you were to clone the JS9 repository:
````
git clone https://github.com/ericmandel/js9
````
and load the JS9 JS and CSS files locally, your test will work, either with a local web server or even with the file:// URI (note that Chrome needs the --allow-file-access-from-files switch for file:// URIs).

**Comment by andreatramacere** [comment]
Thanks for the reply. But after cloning the repo, and changing the code, I still get the same problem.

```
<html>
            <head>
              <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
              <meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1" > 
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <link type="image/x-icon" rel="shortcut icon" href="./favicon.ico">
              <link type="text/css" rel="stylesheet" href="js9/js9support.css">
              <link type="text/css" rel="stylesheet" href="js9/js9.css">
              <script type="text/javascript" src="js9/js9prefs.js"></script>
              <script type="text/javascript" src="js9/js9support.min.js"></script>
              <script type="text/javascript" src="js9/js9.min.js"></script>
              <script type="text/javascript" src="js9/js9plugins.js"></script>
                </head>
            <body>


            <center><font size="+1">
            </font></center>
            <table cellspacing="30">
            <tr valign="top">
            <td>	
            </td>
            <td>	
            <tr valign="top">
            <td>
            <div class="JS9Menubar"></div>
            <div class="JS9"></div>
            </td>
            <td>
            
            <p>
            </td>
            </tr>
            </table>
            <script type="text/javascript">
              function init(){
                 var idx, obj;
                  
			      JS9.Preload("js9/data/test.fits");
              }
              $(document).ready(function(){
                init();
              });
            </script>
            
        </body>
</html>
```

**Comment by ericmandel** [comment]
Hmmm ... that should work when loading something like:
````
file:///Users/eric/foo.html
````
into Chrome or FF or Safari (all of which I just tried). Any chance you are using Chrome and did not start it from the command line, adding the --allow-file-access-from-files switch? Chrome treats file:// URIs in a more restricted manner ...

Can you please send a screenshot of the javascript console?

**Comment by andreatramacere** [comment]
This is the structure of the directory:
```
.
├── Untitled.ipynb
├── js9
├── micro_app.py
├── test.html
└── test1.html
```
The file I am testing is  test.html, the one I showed int the previous post. The js9 dir  is actually the dir of the git repository. Inside this directory I have placed a directory called data, and into data the file I want to load. I am using Fireforx for testing, and I also add the info that a few weeks ago, I was not having this problem. The screenshot of the console is attached below
<img width="1418" alt="Untitled" src="https://user-images.githubusercontent.com/12498415/65884866-dedc6d00-e399-11e9-897f-30e6ae63bb2f.png">

**Comment by ericmandel** [comment]
This page might be relevant, indicating a change in CORS policy starting with FF 68:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

On my Mac running 69.0.1, I see the following in about:config, which would lead me to believe I should have the same CORS problem ... but do not:

<img width="720" alt="Screen Shot 2019-09-30 at 10 19 06 AM" src="https://user-images.githubusercontent.com/3028875/65887437-eab13a80-e36b-11e9-82ac-0d2377d4631a.png">

As an experiment to help me understand, can you change that param to false and see if things work better for you?

**Comment by andreatramacere** [comment]
Hi,
setting to false it works. Since I am thinking to use js9 in a fronted for webservice, what can I do in order to have it properly working for every  user?
Thanks for your support

**Comment by ericmandel** [comment]
This should not be an issue for web services, since your users will not be using the file:// URI, they will be using a http:// or https:// URL. It's only an issue for testing, when you want to use the local file:// URI and bypass the use of a real web server. (Still no idea why I can do it and you cannot, but I'll have to figure that out and document it.)

You can test your eventual web-based setup by starting a Python web server in the directory with test.html:
````
python -m SimpleHTTPServer 8000
````
Then in your browser (with the param reset to true), load the test page:
````
localhost:8000/test.html
````
Now you are loading everything via a web server, not the file:// URI, so there should be no CORS problem. That's what your users will see.

You can also start up an Apache web server on your Mac (it looks like you are using a Mac) and use that for more robust testing. There are plenty of instructions on the net for configuring Apache, depending on which version of macOS you are running: https://www.dyclassroom.com/howto-mac/how-to-install-apache-mysql-php-on-macos-mojave-10-14. I generally develop using the file:// URI out of habit, but have Apache running for production testing.

Let me know if you have problems with the standard web server approach.

**Comment by ericmandel** [comment]
P.S. Is there any chance you are running FF 68 and not FF 69? My FF 69 works and I am wondering if Mozilla changed the behavior in 69 to work again (I can't reproduce the problems in FF 69).

**Comment by andreatramacere** [comment]
Hi,
again, thanks a lot for your feedback!
1) with python3 I use ```python -m http.server 8000``` and it works fine, even if I place the data directory outside the js9 directory. 
2) regarding my Firefox version it is 69.0.1;


So, to summarise, in my server I just have to install locally the js9 library, and accordingly change the src instruction in the head

**Comment by andreatramacere** [comment]
By the way, with this approach, it works fine also in chrome.

**Comment by ericmandel** [comment]
Yes, once you are using a server and localhost:// instead of file://, all of the problems regarding the use of file:// go away. Now that I understand that FF no longer works, I'll update the documentation to explain things more carefully. I still can't understand why my FF works ...

You definitely should install the JS9 libraries locally. Otherwise, you'll still have CORS problems. Also, the main web page is always a reflection of the current state of development, and you'll  probably want to have more control over which version of the libraries you are loading (e.g. so you can test new JS9 code against your app before deploying it!)

Finally, note that the FITS file paths are relative to the web page (just as is the case for the js and css files you load in the header), and will adhere to any restrictions you specify for access. Thus, any file in the web page's top level directory and sub-directories should be accessible by default.
