### ISSUE TITLE
Load multi extension tile compressed fits report error.

### ISSUE THREAD

**Issue by fockez** [ericmandel/js9#72]
The fits file is write by astropy, all the image extensions are CompImageHDU, so the first HDU is an empty HDU. When I load this kind of fits, it is reported that 

> ERROR from astroem/cfitsio: 1st key not SIMPLE or XTENSION

Could you help me to find the solution. Thanks.

**Comment by ericmandel** [comment]
Can you attach or send a FITS file? I'll be happy to look at it.

**Comment by fockez** [comment]
[20200326_7906_906176_0008.zip](https://github.com/ericmandel/js9/files/4391509/20200326_7906_906176_0008.zip)
Here is the fits file. I can open it with ds9 or astropy correctly.

**Comment by ericmandel** [comment]
@fockez Using that test file, the cfitsio library gets an error in fits_convert_hdr2str(), both in js9 and in non-js9 programs. There is special code in fits_convert_hdr2str() to deal with compressed images, so my first guess was that there is a header parameter that is tripping up cfitsio, especially since I routinely load rice-compressed images in other test files.

And indeed, after messing around with the file, the problem seems to be with the 2 parameters BSCALE and BZERO that come after TFIELDS and before TTYPE1. If I delete them from the file, js9 and non-js9 programs work fine:

<img width="110" alt="Screen Shot 2020-03-27 at 9 15 31 AM" src="https://user-images.githubusercontent.com/3028875/77759685-882fb300-700b-11ea-85ad-0738c290a45e.png">

So I think the options are to move those parameters (I didn't try this but I assume moving them down in the header will help) or else we can submit a bug report to cfitsio. fverify does not complain about these params or their location, so this really might a problem with cfitsio itself.

Let me know how you want to proceed.

**Comment by ericmandel** [comment]
Hello everyone,

A js9 issue regarding rice-compressed images was opened here:

https://github.com/ericmandel/js9/issues/72#issuecomment-604811197

which was traced to an error coming from the fits_convert_hdr2str() routine:

FITSIO status = 252: 1st key not SIMPLE or XTENSION
Extension doesn't start with SIMPLE or XTENSION keyword. (ffrhdu)
BSCALE  =                    1
Error while closing HDU number 0 (ffchdu).

The FITS file in question has BSCALE and BZERO parameters in an odd place in the extension (see attached zip file), but fverify does not complain about them and I don’t see mention of required order in, for example:

https://www.adass.org/adass/proceedings/adass99/P2-42/

Therefore, we are wondering if this is a violation of the image compression spec or a bug in cfitsio. Any help would be appreciated.

I append the FITS file and a test file:

	unzip 20200326_7906_906176_0008.FIT.zip
	gcc -o tfits tfits.c …
	./tfits 20200326_7906_906176_0008.FIT'[1]'

to see the error.

Regards,

Eric

**Comment by fockez** [comment]
Thanks for your work on that. I think for now, if move header keyword position would help, that's simple enough, right?

**Comment by ericmandel** [comment]
Yes, if you have control over the order in which the keywords are written, I'd move the BSCALE and BZERO params to some place after the Z params. I did that and was able to load the FITS file.

**Comment by ericmandel** [comment]
@fockez Were you able to move the BSCALE and BZERO parameters  and then use JS9 to display the file? The cfitsio team would especially like to know ... if you have worked around the problem in that way, they can put it into a less urgent queue for fixing.

**Comment by fockez** [comment]
Yes, if I adjust all the extensions' header order, it can be read by js9. Thanks. @ericmandel

**Comment by ericmandel** [comment]
I'll close this, then, but will update it if cfitsio gets fixed.
