### ISSUE TITLE
Q: is there a query parameters to load image from CORS server?

### ISSUE THREAD

**Issue by hombit** [ericmandel/js9#85]
There is a `?url=<URL>` query parameter which allows to load a FITS file, but if I use a url to the server responses with `access-control-allow-origin: *‘ I see an alert "ERROR: could not retrieve: <URL>". Is there any way to load a file from a CORS server adding query parameters to `https://js9.si.edu/` (or any other JS9 web installation)?

**Comment by ericmandel** [comment]
As a baseline, I just did this successfully (not to a CORS server):
````
https://js9.si.edu/?url=https://hea-www.cfa.harvard.edu/~eric/coma.fits.gz
````
The above caused LoadProxy() to download the FITS file and then display it. 

Are you saying that the JS9 website doesn't do this same thing correctly when accessing a FITS file from a CORS server, or are you saying that you want to use your own JS9-enabled server  without supporting LoadProxy?

In either case, if you send me a URL like the one above, but to a CORS server, I can either check for a bug or see what would be involved in using Load instead of LoadProxy (but can't promise anything!)

**Comment by hombit** [comment]
Thanks!

> Are you saying that the JS9 website doesn't do this same thing correctly when accessing a FITS file from a CORS server

I think this is what I'm trying to say: I'm using some proxy which is not JS9-enabled server and which returns `access-control-allow-origin: *`. So `JS9.Load` works for this URL, but `JS9.LoadProxy` doesn't. So it really looks like my issue is happening because `?url=<URL>` leads to call of `JS9.LoadProxy` instead of `JS9.Load`.

The URL i'm checking it with:
```
http://js9.si.edu/?url=https://uci.fits.ztf.snad.space/products/sci/2019/0314/432616/ztf_20190314432616_000633_zr_c07_o_q4_sciimg.fits
```

**Comment by ericmandel** [comment]
Hmmm ... I cannot retrieve that URL using a vanilla program like wget on the main JS9 web site:

````
[eric@js9 ~/tmp]$ wget "https://uci.fits.ztf.snad.space/products/sci/2019/0314/432616/ztf_20190314432616_000633_zr_c07_o_q4_sciimg.fits"
--2022-05-19 17:20:11--  https://uci.fits.ztf.snad.space/products/sci/2019/0314/432616/ztf_20190314432616_000633_zr_c07_o_q4_sciimg.fits
...
ERROR: cannot verify uci.fits.ztf.snad.space's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to uci.fits.ztf.snad.space insecurely, use `--no-check-certificate'.
````

But I can easily load it onto my local machine, where I don't have the same level of checks running as on our production site:

<img width="1148" alt="Screen Shot 2022-05-19 at 5 15 59 PM" src="https://user-images.githubusercontent.com/3028875/169406101-e1c2e1de-c361-457b-8814-9d00285d02f1.png">

So I think the JS9 software is fine but the question is what to do about an expired cert. Are you associated with that group, so that you could ask them to update the expired SSL cert?

**Comment by hombit** [comment]
I'm the guy who maintains this server, and I believe certificate is fine: on my machine both `wget` and `curl` can download this file, `openssl` says everything is ok, all my browsers open this file. Could you try to update your CA database?
```sh
# openssl s_client -showcerts -connect uci.fits.ztf
.snad.space:443
CONNECTED(00000005)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = uci.fits.ztf.snad.space
verify return:1
...
```
<img width="587" alt="image" src="https://user-images.githubusercontent.com/1784493/169408606-3b5adf11-9e42-4e9c-a442-cb66c66b2861.png">

**Comment by hombit** [comment]
When I go to https://js9.si.edu and type in the console `JS9.Load` it loads the file
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/1784493/169409448-20c9bf90-80bd-4e30-ba5b-4954411376d7.png">

But `JS9.LoadProxy` doesn't
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/1784493/169409512-67cb8260-7c6e-462d-b913-ce5ef4ab7631.png">

**Comment by ericmandel** [comment]
Right, LoadProxy is using wget, while Load is just a straight XHR fetch. I'll ping our sysadmin about the wget problem and see if they can do something.

I assume you specifically want the file to load with the page itself, and not simply use File -> open remote ... menu option with the CORS server option set:

<img width="987" alt="Screen Shot 2022-05-19 at 5 49 16 PM" src="https://user-images.githubusercontent.com/3028875/169410416-b59a065c-47d4-4dc1-9419-3b0f1b746e26.png">

**Comment by hombit** [comment]
Year, I'd like to redirect users to https://js9.si.edu/js9/js9.html with some `url,pan,zoom` query parameters. I hope it is not a harmful usage of your site

**Comment by hombit** [comment]
BTW, I thought that FITS files will not be downloaded by your backend and users will just load some JS and CSS...

**Comment by hombit** [comment]
What do you think about this behavior: check first if `JS9.Load` works (I believe it will not download the body if something wrong with CORS headers) and use `JS9.LoadProxy` if it doesn't?

**Comment by ericmandel** [comment]
That's a fine use for the js9 website ... I believe there are entire classes using the site in that way. js9.si.edu is a decent machine and we don't expect to grow beyond its capabilities ...

LoadProxy() is special and it does download the FITS file onto the server ... that's the only way I can think of loading FITS from a non-CORS site (jsonp is too hacky, uggh) and proxy loading does have the benefit of making the back-end analysis available to the retrieved FITS file.

I'm not in love with the idea of trying Load() first, although I take your point that it might not take all that long to error out ... but no matter, sysadmin just fixed the CA database. so you should be all set:

![Screen Shot 2022-05-19 at 6 53 17 PM](https://user-images.githubusercontent.com/3028875/169417751-32b9ae18-8c0c-4c9b-b451-2cf4b3439fac.png)

You might want to use a pristine js9 display without  first loading the casa demo image. Just use this URL instead of index.html:
````
https://js9.si.edu/js9/js9.html?url=https://uci.fits.ztf.snad.space/products/sci/2019/0314/432616/ztf_20190314432616_000633_zr_c07_o_q4_sciimg.fits
````

**Comment by hombit** [comment]
Thank you!

**Comment by hombit** [comment]
BTW, is there any list of available query parameters?

**Comment by ericmandel** [comment]
Huh, looks like I forgot to document that! Aside from colormap and scale params, I believe you can set panning parameters:
````
	    if( (JS9.notNull(localOpts.x)  && JS9.notNull(localOpts.y))   ||
		(JS9.notNull(localOpts.px) && JS9.notNull(localOpts.py))  ||
		(JS9.notNull(localOpts.ra) && JS9.notNull(localOpts.dec)) ||
		(JS9.notNull(localOpts.wcs))                              ){
		this.setPan(localOpts);
````
(px,py are the file image positions, x,y are displayed image positions, often the same if you are displaying the whole image ... ra and dec are in degrees) and also regions.

**Comment by hombit** [comment]
Thank you! Is it possible to set flip?

**Comment by ericmandel** [comment]
Yes, sorry, you should be able to set anything contained in JS9.imageOpts: flip, rotate, etc. In my answer above, I was only mentioning the params that were handled specially.

**Comment by hombit** [comment]
Thank you for all your help! I think that there is something wrong with flipping, but I'd open new issue on this
